config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'events#index'

  resources :events do
    resources :guests
  end

  resources :places
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :place

  validates :name, presence: true
  validates :starts_at, presence: true
  validates :ends_at, presence: true

  has_many :guests, dependent: :destroy

  def guest_count
    guests.count
  end
end

app/models/guest.rb
# frozen_string_literal: true

class Guest < ApplicationRecord
  belongs_to :event

  validates :name, presence: true
  validates :email, presence: true
end

app/models/place.rb
# frozen_string_literal: true

class Place < ApplicationRecord
  has_many :events, dependent: :destroy

  validates :name, presence: true

  def has_events?
    events.exists?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def index
    sort_column = safe_sort_column
    sort_direction = safe_sort_direction
    @events = Event.order("#{sort_column} #{sort_direction}").page(params[:page]).per(10)
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, notice: 'Event created'
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: 'Event updated'
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path, notice: 'Event deleted'
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :place_id, :starts_at, :ends_at)
  end

  def safe_sort_column
    %w[name starts_at].include?(params[:sort]) ? params[:sort] : 'starts_at'
  end

  def safe_sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/controllers/guests_controller.rb
# frozen_string_literal: true

class GuestsController < ApplicationController
  # OBVIOUSLY this would only ever be used for localhost purposes only
  protect_from_forgery with: :null_session
  def index
    @guests = Guest.where(event_id: params[:event_id])
    render json: @guests, status: :ok
  end

  def create
    @guest = Guest.new(guest_params)
    if @guest.save
      render json: @guest, status: :created
    else
      render json: { errors: @guest.errors.full_messages }, status: :unprocessable_entity
    end
  end

  # Note - not used in the UI currently (but this is what it could be if webapp needs to edit guests)
  def update
    @guest = Guest.find(params[:id])
    if @guest.update(guest_params)
      render json: @guest, status: :ok
    else
      render json: { errors: @guest.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    @guest = Guest.find(params[:id])
    @guest.destroy
    head :ok
  end

  private

  def guest_params
    params.require(:guest).permit(:name, :email).merge(event_id: params[:event_id])
  end
end

app/controllers/places_controller.rb
# frozen_string_literal: true

class PlacesController < ApplicationController
  def index
    @places = Place.all
  end

  def show
    @place = Place.find(params[:id])
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      redirect_to @place, notice: 'Place created'
    else
      render :new
    end
  end

  def edit
    @place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])
    if @place.update(place_params)
      redirect_to @place, notice: 'Place updated'
    else
      render :edit
    end
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    redirect_to places_path, notice: 'Place deleted'
  end

  private

  def place_params
    params.require(:place).permit(:name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def dynamic_title
    case controller_name
    when 'events'
      'Events Manager'
    when 'places'
      'Places Manager'
    else
      'Welcome to Events Manager'
    end
  end

  def navigation_title
    case controller_name
    when 'places'
      link_to dynamic_title, places_path
    when 'events'
      link_to dynamic_title, events_path
    else
      dynamic_title
    end
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/views/events/_event.html.erb
<li class="event">
  <h3 class="event__name"><%= link_to event.name, event %></h3>
  <div class="event__place"><%= event.place.name %></div>
  <div class="event__description"><%= event.description %></div>
  <div class="event__guest_count"><%= event.guest_count %> guests.</div>
  <div class="event__dates">
    <span class="event__dates__date"><%= event.starts_at.to_fs(:long) %></span>
    to
    <span class="event__dates__date"><%= event.ends_at.to_fs(:long) %></span>
  </div>
</li>

app/views/events/_form.html.erb
<%= form_with model: event, class: "form" do |form| %>
  <div class="form-row">
    <%= form.label :name %>
    <%= form.text_field :name %>
    <% if event.errors[:name].any? %>
      <p class="form-row__error">
        <%= event.errors.where(:name).map(&:full_message).to_sentence %>
      </p>
    <% end %>
  </div>

  <div class="form-row">
    <%= form.label :description %>
    <%= form.text_area :description %>
    <% if event.errors[:description].any? %>
      <p class="form-row__error">
        <%= event.errors.where(:name).map(&:full_message).to_sentence %>
      </p>
    <% end %>
  </div>

  <div class="form-row">
    <%= form.label :place_id %>
    <%= form.collection_select :place_id, Place.all, :id, :name %>
    <% if event.errors[:place_id].any? %>
      <p class="form-row__error">
        <%= event.errors.where(:place_id).map(&:full_message).to_sentence %>
      </p>
    <% end %>
  </div>

  <div class="form-row">
    <%= form.label :starts_at %>
    <%= form.datetime_select :starts_at %>
    <% if event.errors[:starts_at].any? %>
      <p class="form-row__error">
        <%= event.errors.where(:starts_at).map(&:full_message).to_sentence %>
      </p>
    <% end %>
  </div>

  <div class="form-row">
    <%= form.label :ends_at %>
    <%= form.datetime_select :ends_at %>
    <% if event.errors[:ends_at].any? %>
      <p class="form-row__error">
        <%= event.errors.where(:ends_at).map(&:full_message).to_sentence %>
      </p>
    <% end %>
  </div>

  <%= form.submit %>
<% end %>

app/views/events/edit.html.erb
<h2>Edit Event: <%= @event.name %></h2>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<h2>Upcoming Events</h2>

<div class="sort-dropdown">
  <%= form_with url: events_path, method: :get, local: true do %>
    <label for="sort">Sort by:</label>
    <%= select_tag :sort, options_for_select([['Name', 'name'], ['Start Date', 'starts_at']], params[:sort]), onchange: 'this.form.submit();' %>
    <%= hidden_field_tag :direction, params[:direction] || 'asc' %>
  <% end %>
</div>

<ul class="event-list">
  <%= render @events %>
</ul>

<%= paginate @events %>

app/views/events/new.html.erb
<h2>Create an Event</h2>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<section class="event-details">
  <h2>Event Details</h2>

  <h3><%= @event.name %></h3>

  <div class="event__dates">
    <span class="event__dates__date"><%= @event.starts_at.to_fs(:long) %></span>
    to
    <span class="event__dates__date"><%= @event.ends_at.to_fs(:long) %></span>
  </div>

  <div>Location: <span class="event__place"><%= @event.place.name %></span></div>

  <div class="event__description"><%= @event.description %></div>

  <div class="event__actions">
    <%= link_to "Edit", edit_event_path(@event), class: "button" %>
    <%= button_to "Delete", event_path(@event), class: "button", method: :delete, confirm: "Are you sure?" %>
  </div>
</section>

<section class="event-guests">
  <h2 id="guest-manager-heading">Guests</h2>

  <div id="x-event-guests-manager">
    Guests Manager Goes Here
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= dynamic_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </head>

  <body>
    <header>
      <div class="navigation_title">
        <h1><%= navigation_title %></h1>
        <div class="navigation-dropdown">
          <label for="resource-select">Go to:</label>
          <select id="resource-select" onchange="if (this.value) window.location.href=this.value;">
            <option value="" disabled selected>Select a resource</option>
            <option value="<%= places_path %>" <%= 'disabled' if controller_name == 'places' %>>Places</option>
            <option value="<%= events_path %>" <%= 'disabled' if controller_name == 'events' %>>Events</option>
          </select>
        </div>
      </div>
      <nav>
        <% if controller_name == "events" %>
          <%= link_to "Create an Event", new_event_path %>
        <% elsif controller_name == "places" %>
          <%= link_to "Create a Place", new_place_path %>
        <% else %>
          <%= link_to "Home", root_path %>
        <% end %>
      </nav>
    </header>

    <% if flash.notice.present? %>
      <aside class="flash">
        <%= flash.notice %>
      </aside>
    <% end %>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_with model: place, class: "form" do |form| %>
  <div class="form-row">
    <%= form.label :name %>
    <%= form.text_field :name %>
    <% if place.errors[:name].any? %>
      <p class="form-row__error">
        <%= place.errors.where(:name).map(&:full_message).to_sentence %>
      </p>
    <% end %>
  </div>

  <%= form.submit %>
<% end %>

app/views/places/_place.html.erb
<li class="place">
  <h3 class="place__name"><%= link_to place.name, place %></h3>
</li>

app/views/places/edit.html.erb
<h2>Edit Place: <%= @place.name %></h2>

<%= render "form", place: @place %>

app/views/places/index.html.erb
<h2>Current Places</h2>

<ul class="place-list">
  <%= render @places %>
</ul>

app/views/places/new.html.erb
<h2>Create a Place</h2>

<%= render "form", place: @place %>

app/views/places/show.html.erb
<section class="place-details">
  <h2>Place Details</h2>

  <h3><%= @place.name %></h3>

  <div class="place__actions">
    <%= link_to "Edit", edit_place_path(@place), class: "button" %>
    <%= button_to "Delete", place_path(@place), class: "button", method: :delete, confirm: "Are you sure?", disabled: @place.has_events? %>
  </div>
</section>